/**
 * @type {{CACHE_KEY_PREFIX: string, SLACK: {CHANNEL_ID: string, ENABLED: boolean}, WEBHOOK: {CALL_URL: string, FAILURE_CALL_URL: string, ENABLED: boolean}, EMAIL: {FAILURE_SUBJECT: string, PORT: number, HOST: string, SECURE: boolean, SUBJECT: string, TO: string[]}, DEBUG: boolean, TWITTER: {ENABLED: boolean}, CHECKER: {MESSAGE_FORMAT: (function(*, *, *): string), METHOD: string, PARSE_MODE: string, HTML: {FAILURE_SELECTOR: string, SELECTOR_PATH: string}, JSON: {FAILURE_SELECTOR: string, SELECTOR_PATH: string}, TEXT: {FAILURE_CONTENT: string, CONTENT: string}, SCENARIO: string, NOTIFY_SCENARIO_FAILURES: boolean, URL: string}, TELEGRAM: {CHAT_IDS: string[], ENABLED: boolean}}}
 */
const scenarios = {
  RESPONSE_EQUAL: 'RESPONSE_EQUAL',
  RESPONSE_NOT_EQUAL: 'RESPONSE_NOT_EQUAL',
  RESPONSE_GREATER_THAN: 'RESPONSE_GREATER_THAN',
  RESPONSE_LOWER_THAN: 'RESPONSE_LOWER_THAN',
  RESPONSE_CONTAINS: 'RESPONSE_CONTAINS',
  RESPONSE_NOT_CONTAINS: 'RESPONSE_NOT_CONTAINS',
  HTML_SELECTOR_EXIST: 'HTML_SELECTOR_EXIST',
  HTML_SELECTOR_NOT_EXIST: 'HTML_SELECTOR_NOT_EXIST',
  HTML_SELECTOR_CONTENT_EQUAL: 'HTML_SELECTOR_CONTENT_EQUAL',
  HTML_SELECTOR_CONTENT_NOT_EQUAL: 'HTML_SELECTOR_CONTENT_NOT_EQUAL',
  HTML_SELECTOR_CONTENT_GREATER_THAN: 'HTML_SELECTOR_CONTENT_GREATER_THAN',
  HTML_SELECTOR_CONTENT_LOWER_THAN: 'HTML_SELECTOR_CONTENT_LOWER_THAN',
  HTML_SELECTOR_CONTENT_CONTAINS: 'HTML_SELECTOR_CONTENT_CONTAINS',
  HTML_SELECTOR_CONTENT_NOT_CONTAINS: 'HTML_SELECTOR_CONTENT_NOT_CONTAINS',
  JSON_SELECTOR_CONTENT_EXIST: 'JSON_SELECTOR_CONTENT_EXIST',
  JSON_SELECTOR_CONTENT_NOT_EXIST: 'JSON_SELECTOR_CONTENT_NOT_EXIST',
  JSON_SELECTOR_CONTENT_EQUAL: 'JSON_SELECTOR_CONTENT_EQUAL',
  JSON_SELECTOR_CONTENT_NOT_EQUAL: 'JSON_SELECTOR_CONTENT_NOT_EQUAL',
  JSON_SELECTOR_CONTENT_GREATER_THAN: 'JSON_SELECTOR_CONTENT_GREATER_THAN',
  JSON_SELECTOR_CONTENT_LOWER_THAN: 'JSON_SELECTOR_CONTENT_LOWER_THAN',
  JSON_SELECTOR_CONTENT_CONTAINS: 'JSON_SELECTOR_CONTENT_CONTAINS',
  JSON_SELECTOR_CONTENT_NOT_CONTAINS: 'JSON_SELECTOR_CONTENT_NOT_CONTAINS',
};

export default {
  DEBUG: true,
  CACHE_KEY_PREFIX: 'pulse-cache',
  NOTIFY_SCENARIO_FAILURES: true,
  HTTP: {
    URL: 'http://localhost:3000',
    METHOD: 'GET',
    PARSE_MODE: 'TEXT', // TEXT, HTML, JSON
    HTML_SELECTOR: '#some_id > .class',
    JSON_SELECTOR: '.price',
    VALUE_TO_CHECK: 'some value to be checked', // if you want to check selector value
    SCENARIO: scenarios.RESPONSE_CONTAINS,
    MESSAGE_FORMAT: ({ title, url, $body }) => `
      ${title}\n\n
      ${url}\n\n
      ${$body
        .find('h1')
        .text()
        .replace(/\\r?\\n|\\r|\\t/gm, '')
        .trim()}
    `,
  },
  EMAIL: {
    HOST: 'smtp.gmail.com',
    PORT: 465,
    SECURE: true,
    SUBJECT: 'New Items',
    FAILURE_SUBJECT: 'New Items',
    TO: ['your@email.com', 'another@email.com'],
  },
  TELEGRAM: {
    ENABLED: false,
    CHAT_IDS: ['YOUR_TELEGRAM_CHAT_ID'],
  },
  SLACK: {
    ENABLED: false,
    CHANNEL_ID: 'YOUR_SLACK_CHANNEL_ID',
  },
  WEBHOOK: {
    ENABLED: false,
    CALL_URL: 'YOUR_WEBHOOK_URL',
    FAILURE_CALL_URL: 'YOUR_FAILURE_WEBHOOK_URL',
  },
  TWITTER: {
    ENABLED: false,
  },
};
